server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Gérer le routage d'Angular (empêche les erreurs 404 lors du rafraîchissement)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Transférer toutes les requêtes /api vers notre conteneur Backend
    location /api/ {
        proxy_pass http://expenso-backend:8090/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
